### ISSUE TITLE
Running under rubinius 2.4.0 jobs don't obey their schedule

### ISSUE THREAD

**Issue by shadoi** [facto/fist_of_fury#3]
If I run a job with with something like: 
```ruby
  include FistOfFury::Recurrent

  recurs { minutely(2) }
```

Under MRI 2.1.4, and puma, it works as desired and only runs this job once every 2 minutes.

If I run it under Rubinius 2.4.0 and puma, it spawns MANY MANY threads all enqueuing the job endlessly.  I haven't dug into the reason why yet, but was hoping you had some inkling.

**Comment by facto** [comment]
Sorry to get to this so late. 

I think at least part of this is related to https://github.com/facto/fist_of_fury/issues/2. I haven't tested under Rubinius so I can't comment further. If you've found out anything since reporting this, please let me know.

Closing for now.

Thanks!
