### ISSUE TITLE
[Jruby] Thread leak

### ISSUE THREAD

**Issue by swistaczek** [facto/fist_of_fury#5]
Hey,
Issue look simillar to that one occuring in sidetiq which was also using ice_cube in version 0.12.0. Please downgrade ice_cube to more stable version (0.11.1).

**Comment by facto** [comment]
Thanks for reporting this. More info: https://github.com/tobiassvn/sidetiq/issues/107

**Comment by facto** [comment]
I will lock the repo to 0.11.x to avoid this for now. Would be great if you or someone else could test 0.12.1 to see if it fixes the issue.

See: https://github.com/facto/fist_of_fury/issues/6

**Comment by facto** [comment]
Fixed in 0.2.7
